command_timeout = 1000

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[time]
disabled = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 25
style = "bold red"

[memory_usage]
disabled = false
threshold = 80

[directory]
truncation_length = 5
#suffix = "â–¶"
#style = "white bold bg:#00819e"
style = "bold #00819e"
fish_style_pwd_dir_length = 1
# before_repo_root_style = "bold #AA1111"
repo_root_style = "bold #62c1be"

#[git_branch]
#style = "bg:purple bold"
#suffix = "â–¶"

#[git_status]
#style = "bg:purple bold "
#suffix = "\ue0b0"

[git_commit]
tag_disabled = false

[container]
disabled = true
