[character]
symbol = "âœ"
use_symbol_for_status = true

[time]
disabled = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 25
style = "bold red"

[memory_usage]
disabled = false
threshold = 80
show_swap = false

[directory]
truncation_length = 3
#suffix = "â–¶"
#style = "white bold bg:#00819e"
style = "bold #00819e"
fish_style_pwd_dir_length = 1

#[git_branch]
#style = "bg:purple bold"
#suffix = "â–¶"

#[git_status]
#style = "bg:purple bold "
#suffix = "\ue0b0"
