
# Fallback icon
default_icon = "â€¢"

# Format string for determining the new workspace name. Placeholders are
# %n  number of the workspace
# %i  icon from the map below
format_str = "%n %i "

# Separator between workspace icons
icon_separator = " "

[icons]
"firefox" = "ï‰©"
"google-chrome" = "ï‰¨"
"chromium" = "ï‰¨"
"alacritty" = "ï„ "
"kitty" = "ï„ "
"terminator" = "ï„ "
"chrome-eoficlgicibe" = "ïª"
"chrome-ompifgpmd" = "ï¡ "
"emacs" = "ï‰‰ "
"thunar" = "ï» "
"org.kde.dolphin" = "ï» "
"org.gnome.nautilus" = "ï» "
"code" = "ï„¡ "
"spotify" = "ï†¼ "
"tm" = "ó±©¼"
"pm" = "ïƒ"
"libreoffice" = "ó±©¼"
"evince" = "ï‡"
"okular" = "ï‡"
"zathura" = "ï‡"
"signal" = "ó°¡"
"teams" = "ó°¡"
"thunderbird" = "ó°‡®"
"evolution" = "ó°‡®"
"electron" = "î˜® "
"wine" = "ğŸ·"
"shotwell" = "ï€¾"
"imv" = "ï€¾"
"zoom" = "ï‘‡"
"bitwarden" = "ï€£"
"desktopeditors" = "ïœ«"
"nm-connection" = "ğŸ–§ "
"pavucontrol" = "ğŸ•ª"
"draw.io" = "ï£ª"
"keepass" = "ï‚„"
"wfica" = "ï…º"
"remmina" = "ï…º"
"kicad" = "ï‹›"
"org.wireshark" = "ï¯³"
"wireshark" = "ğŸ–§"
"ffpwa-01jn36ppz49jp0pzrn3fe62y6j" = "ïª"
"swappy" = "ï€¾ "
