
# Fallback icon
default_icon = "â€¢"

# Format string for determining the new workspace name. Placeholders are
# %n  number of the workspace
# %i  icon from the map below
format_str = "%n %i "

# Separator between workspace icons
icon_separator = " "

[icons]
"firefox" = "ï‰©"
"chrome" = "ï‰¨"
"chromium" = "ï‰¨"
"alacritty" = "ï„ "
"terminator" = "ï„ "
"emacs" = "ï‰‰ "
"thunar" = "ï» "
"org.kde.dolphin" = "ï» "
"org.gnome.nautilus" = "ï» "
"code" = "ï„¡ "
"spotify" = "ï†¼ "
"tm" = "ïœ«"
"pm" = "ïƒ "
"libreoffice" = "ïœ«"
"evince" = "ï‡ "
"okular" = "ï‡ "
"zathura" = "ï‡ "
"signal" = "ï¡  "
"teams" = "ï¡  "
"thunderbird" = "ïª"
"electron" = "î˜® "
"wine" = "ğŸ·"
"shotwell" = "ï€¾ "
"imv" = "ï€¾ "
"zoom" = "ï‘‡ "
"bitwarden" = "ï€£"
"desktopeditors" = "ïœ«"
"nm-connection" = "ğŸ–§ "
"pavucontrol" = "ğŸ•ª"
"draw.io" = "ï£ª"
